name: Publish Docker images

on:
  push:
    branches: [ main ]
    tags: [ "v*", "release-*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # allows push to GHCR using GITHUB_TOKEN
    strategy:
      matrix:
        include:
          - name: api
            context: .
            dockerfile: docker/api.Dockerfile
          - name: web
            context: ./ui
            dockerfile: docker/web.Dockerfile
          - name: cli
            context: .
            dockerfile: docker/cli.Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---- GHCR login (uses built-in GITHUB_TOKEN) ----
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---- (Optional) Docker Hub login ----
      # Add DOCKERHUB_USERNAME / DOCKERHUB_TOKEN in repo secrets to enable
      # - name: Login to Docker Hub
      #   if: secrets.DOCKERHUB_TOKEN != ''
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: vars
        run: |
          # tag latest on main; use the tag name on tag builds; fallback to sha
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          else
            echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ matrix.name }}:${{ steps.vars.outputs.TAG }}

      # - name: Build & Push (Docker Hub)  # optional
      #   if: secrets.DOCKERHUB_TOKEN != ''
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ${{ matrix.context }}
      #     file: ${{ matrix.dockerfile }}
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: |
      #       ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-${{ matrix.name }}:${{ steps.vars.outputs.TAG }}
